services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    networks:
      - adguard
    ports:
      - "${HOST_IP}:53:53/tcp"
      - "${HOST_IP}:53:53/udp"
    restart: unless-stopped
    volumes:
      - $HOME/.adguard/work:/opt/adguardhome/work
      - $HOME/.adguard/conf:/opt/adguardhome/conf

networks:
  adguard:
    name: adguard
