services:
  caddy:
    container_name: caddy
    env_file:
      - .env
    image: ghcr.io/caddybuilds/caddy-cloudflare:2
    networks:
      - adguard
      - bentopdf
      - homepage
      - karakeep
      - silverbullet
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  adguard:
    external: true
  bentopdf:
    external: true
  homepage:
    external: true
  karakeep:
    external: true
  silverbullet:
    external: true
