services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped

    environment:
      - JWT_SECRET={JWT_SECRET} # will use randomUUID() if unset
      - HTTP_ALLOWED=true # uncomment this if accessing it over a non-https connection

    volumes:
      - $HOME/.convertx:/app/data

    networks:
      - homelab

networks:
  homelab:
    external: true
