services:
  bentopdf:
    container_name: bentopdf
    image: ghcr.io/alam00000/bentopdf-simple:2.8.8
    networks:
      - bentopdf
    restart: unless-stopped

networks:
  bentopdf:
    name: bentopdf
