services:
  bentopdf:
    container_name: bentopdf
    image: ghcr.io/alam00000/bentopdf-simple:latest

    expose:
      - 8080

    networks:
      - homelab

    restart: unless-stopped

networks:
  homelab:
    external: true
